package views;



import com.toedter.calendar.JCalendar;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;


/**
 *
 * @author braul
 */
public class VentanaPartidos extends javax.swing.JPanel {


    /**
     * Creates new form Partidos
     */
    public VentanaPartidos() {
        initComponents(); 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelTabla = new javax.swing.JPanel();
        panelDetallesPartido = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_ClvPartido = new javax.swing.JTextField();
        tf_NomLugar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cb_EquipoUno = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cb_EquipoDos = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tf_FechaPartido = new javax.swing.JTextField();
        calendario = new com.toedter.calendar.JCalendar();
        cb_HoraPartido = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Partidos = new javax.swing.JTable();
        btn_Nuevo = new javax.swing.JButton();
        btn_Editar = new javax.swing.JButton();
        btn_Borrar = new javax.swing.JButton();
        btn_Guardar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(243, 243, 243));
        setMaximumSize(new java.awt.Dimension(980, 690));
        setMinimumSize(new java.awt.Dimension(980, 690));
        setPreferredSize(new java.awt.Dimension(980, 690));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Partidos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        panelTabla.setLayout(new java.awt.BorderLayout());

        panelDetallesPartido.setMaximumSize(new java.awt.Dimension(300, 134));
        panelDetallesPartido.setMinimumSize(new java.awt.Dimension(300, 134));
        panelDetallesPartido.setPreferredSize(new java.awt.Dimension(300, 134));
        panelDetallesPartido.setVerifyInputWhenFocusTarget(false);

        jLabel2.setText("Clave del Partido(#):");

        jLabel3.setText("Nobre del estadio:");

        tf_ClvPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ClvPartidoActionPerformed(evt);
            }
        });

        jLabel4.setText("Equipo local:");

        cb_EquipoUno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_EquipoUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_EquipoUnoActionPerformed(evt);
            }
        });

        jLabel5.setText("Equipo visitante:");

        cb_EquipoDos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Fecha:");

        calendario.setPreferredSize(new java.awt.Dimension(303, 241));

        jLabel7.setText("Hora:");

        javax.swing.GroupLayout panelDetallesPartidoLayout = new javax.swing.GroupLayout(panelDetallesPartido);
        panelDetallesPartido.setLayout(panelDetallesPartidoLayout);
        panelDetallesPartidoLayout.setHorizontalGroup(
            panelDetallesPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesPartidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetallesPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetallesPartidoLayout.createSequentialGroup()
                        .addGroup(panelDetallesPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDetallesPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addGroup(panelDetallesPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)))
                            .addGroup(panelDetallesPartidoLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDetallesPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_NomLugar)
                            .addComponent(tf_ClvPartido)
                            .addComponent(cb_EquipoUno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_EquipoDos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_FechaPartido)))
                    .addGroup(panelDetallesPartidoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(panelDetallesPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelDetallesPartidoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7))
                            .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetallesPartidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cb_HoraPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelDetallesPartidoLayout.setVerticalGroup(
            panelDetallesPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesPartidoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelDetallesPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_ClvPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelDetallesPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_NomLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panelDetallesPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_EquipoUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelDetallesPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cb_EquipoDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelDetallesPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_FechaPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetallesPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_HoraPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        panelTabla.add(panelDetallesPartido, java.awt.BorderLayout.LINE_END);

        tb_Partidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_Partidos);

        panelTabla.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(panelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 980, 560));

        btn_Nuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\braul\\Desktop\\carpetas escritorio\\proyectobeibol\\Proyecto-Const.SW-Beisbol\\BeiboletosJavaProject\\BEISBOLETOS\\src\\vistas\\images\\plus-circle.png")); // NOI18N
        btn_Nuevo.setText("Nuevo");
        btn_Nuevo.setBorderPainted(false);
        btn_Nuevo.setContentAreaFilled(false);
        btn_Nuevo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btn_Nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Nuevo.setPreferredSize(new java.awt.Dimension(71, 24));
        btn_Nuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(btn_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 80));

        btn_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/images/pencil-square.png"))); // NOI18N
        btn_Editar.setText("Editar");
        btn_Editar.setBorderPainted(false);
        btn_Editar.setContentAreaFilled(false);
        btn_Editar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Editar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(btn_Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, 80));

        btn_Borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/images/archive-box-x-mark.png"))); // NOI18N
        btn_Borrar.setText("Borrar");
        btn_Borrar.setBorderPainted(false);
        btn_Borrar.setContentAreaFilled(false);
        btn_Borrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Borrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(btn_Borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 80, 80));

        btn_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/images/check-circle.png"))); // NOI18N
        btn_Guardar.setText("Guardar");
        btn_Guardar.setBorderPainted(false);
        btn_Guardar.setContentAreaFilled(false);
        btn_Guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Guardar.setPreferredSize(new java.awt.Dimension(70, 76));
        btn_Guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(btn_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 80, 80));

        btn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/images/x-circle.png"))); // NOI18N
        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.setBorderPainted(false);
        btn_Cancelar.setContentAreaFilled(false);
        btn_Cancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Cancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });
        add(btn_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void tf_ClvPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ClvPartidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ClvPartidoActionPerformed

    private void cb_EquipoUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_EquipoUnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_EquipoUnoActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CancelarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Borrar;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Editar;
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_Nuevo;
    private com.toedter.calendar.JCalendar calendario;
    private javax.swing.JComboBox<String> cb_EquipoDos;
    private javax.swing.JComboBox<String> cb_EquipoUno;
    private javax.swing.JComboBox<String> cb_HoraPartido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelDetallesPartido;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JTable tb_Partidos;
    private javax.swing.JTextField tf_ClvPartido;
    private javax.swing.JTextField tf_FechaPartido;
    private javax.swing.JTextField tf_NomLugar;
    // End of variables declaration//GEN-END:variables

    public JButton getBtn_Borrar() {
        return btn_Borrar;
    }

    public JButton getBtn_Cancelar() {
        return btn_Cancelar;
    }

    public JButton getBtn_Editar() {
        return btn_Editar;
    }

    public JButton getBtn_Guardar() {
        return btn_Guardar;
    }

    public JButton getBtn_Nuevo() {
        return btn_Nuevo;
    }

    public JTable getTb_Partidos() {
        return tb_Partidos;
    }

    public JTextField getTf_ClvPartido() {
        return tf_ClvPartido;
    }
    
    public JTextField getTf_NomLugar() {
        return tf_NomLugar;
    }
    
    public JComboBox<String> getCb_EquipoUno() {
        return cb_EquipoUno;
    }
    
    public JComboBox<String> getCb_EquipoDos() {
        return cb_EquipoDos;
    }

    public JTextField getTf_FechaPartido() {
        return tf_FechaPartido;
    }

    public JCalendar getCalendario() {
        return calendario;
    }

    public JComboBox<String> getCb_HoraPartido() {
        return cb_HoraPartido;
    }
    
    
}
