
package vistas;
import ModelosD.Equipo;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JTextField;
import mysqlImplements.DAOException;
import mysqlImplements.MySQLDaoManager;


/**
 *
 * @author braul
 */
public class Equipos extends javax.swing.JPanel {

    /**
     * Creates new form Equipos
     */
    public Equipos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        input_Nequipo = new javax.swing.JTextField();
        btn_AgregarEquipo = new javax.swing.JButton();
        input_ClaveEquipo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(980, 690));
        setMinimumSize(new java.awt.Dimension(980, 690));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Equipos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 720, 380));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Agregar equipo");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        input_Nequipo.setText("Nombre del equipo");
        add(input_Nequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 160, 30));

        btn_AgregarEquipo.setText("Agregar");
        btn_AgregarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarEquipoActionPerformed(evt);
            }
        });
        add(btn_AgregarEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 570, -1, -1));

        input_ClaveEquipo.setText("Clave de equipo");
        add(input_ClaveEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 570, 130, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AgregarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarEquipoActionPerformed
        // TODO add your handling code here:
        String nombreEquipo=getInput_Nequipo().getText();
        int claveEquipo = Integer.parseInt( getInput_ClaveEquipo().getText());
        Equipo nuevoEquipo = new Equipo(claveEquipo, nombreEquipo);
        MySQLDaoManager manager = new MySQLDaoManager();
        
        try {
            manager.getEquipoDAO().agregar(nuevoEquipo);
        } catch (DAOException ex) {
            Logger.getLogger(Equipos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        System.out.println("Hola mundo");
    }//GEN-LAST:event_btn_AgregarEquipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AgregarEquipo;
    private javax.swing.JTextField input_ClaveEquipo;
    private javax.swing.JTextField input_Nequipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public JButton getBtn_AgregarEquipo() {
        return btn_AgregarEquipo;
    }

    public JTextField getInput_ClaveEquipo() {
        return input_ClaveEquipo;
    }

    public JTextField getInput_Nequipo() {
        return input_Nequipo;
    }
    
}
