/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import ModelosD.Partido;
import java.util.logging.Level;
import java.util.logging.Logger;
import mysqlImplements.DAOException;
import mysqlImplements.MySQLPartidoDAO;

/**
 *
 * @author braul
 */
public class Partidos extends javax.swing.JPanel {

    /**
     * Creates new form Partidos
     */
    public Partidos() {
        initComponents();
        setMeses();
        setDias();
        setHoras();
        setEquipoUno();
        setEquipoDos();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_crearPartido = new javax.swing.JButton();
        cb_Mes = new javax.swing.JComboBox<>();
        cb_Dia = new javax.swing.JComboBox<>();
        cb_Hora = new javax.swing.JComboBox<>();
        cb_EquipoUno = new javax.swing.JComboBox<>();
        cb_EquipoDos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        input_ClvPartido = new javax.swing.JTextField();
        input_Lugar = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(980, 690));
        setMinimumSize(new java.awt.Dimension(980, 690));
        setPreferredSize(new java.awt.Dimension(980, 690));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Partidos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btn_crearPartido.setText("Crear Partido");
        btn_crearPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearPartidoActionPerformed(evt);
            }
        });
        add(btn_crearPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, -1, -1));

        cb_Mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cb_Mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 130, 30));

        cb_Dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cb_Dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 130, 30));

        cb_Hora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cb_Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 160, 30));

        cb_EquipoUno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cb_EquipoUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 140, 30));

        cb_EquipoDos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cb_EquipoDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 150, 30));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Equipo2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Mes");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Dia");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Hora");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Equipo1");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, 20));

        input_ClvPartido.setText("Clave del partido");
        add(input_ClvPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        input_Lugar.setText("Direccion");
        add(input_Lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_crearPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearPartidoActionPerformed
        // TODO add your handling code here:
        int clave=Integer.parseInt(input_ClvPartido.getText());
        String lugar=input_Lugar.getText();  
        int equipoU = Integer.parseInt(cb_EquipoUno.getSelectedItem().toString());
        int equipoD = Integer.parseInt(cb_EquipoDos.getSelectedItem().toString());
        int hora = Integer.parseInt(cb_Hora.getSelectedItem().toString());
         int Dia = Integer.parseInt(cb_Dia.getSelectedItem().toString());
          int mes = Integer.parseInt(cb_Mes.getSelectedItem().toString());
          Partido nuevoPartido=new Partido(clave, lugar, equipoU, equipoD, hora, Dia, mes);
          MySQLPartidoDAO partidoDAO = new MySQLPartidoDAO();
        try {
            partidoDAO.agregar(nuevoPartido);
        } catch (DAOException ex) {
            Logger.getLogger(Partidos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_crearPartidoActionPerformed
    public void setMeses(){
        int cantidadMeses=12;
        cb_Mes.removeAllItems();
        for (int i=0;i<cantidadMeses;i++){
           int mes = i+1;
           if(i<9){
              cb_Mes.addItem("0"+mes); 
           } else{
               cb_Mes.addItem(""+mes);
           }
           
            
        }
    }
    public void setDias(){
        int dias= 31;
        cb_Dia.removeAllItems();
        for(int i=0;i<dias;i++){
            int diaActual=i+1;
            if(i<9){
              cb_Dia.addItem("0"+diaActual); 
           } else{
               cb_Dia.addItem(""+diaActual);
           }
        }
    }
    public void setHoras(){
        int horasDia=24;
        cb_Hora.removeAllItems();
        for(int i=0;i<horasDia;i++){
            int hora=i;
            if(i<9){
              cb_Hora.addItem("0"+hora); 
           } else{
               cb_Hora.addItem(""+hora);
           }
        }
    }
    public void setEquipoUno(){
        cb_EquipoUno.removeAllItems();
        cb_EquipoUno.addItem("123");
    }
    public void setEquipoDos(){
         cb_EquipoDos.removeAllItems();
        cb_EquipoDos.addItem("342");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_crearPartido;
    private javax.swing.JComboBox<String> cb_Dia;
    private javax.swing.JComboBox<String> cb_EquipoDos;
    private javax.swing.JComboBox<String> cb_EquipoUno;
    private javax.swing.JComboBox<String> cb_Hora;
    private javax.swing.JComboBox<String> cb_Mes;
    private javax.swing.JTextField input_ClvPartido;
    private javax.swing.JTextField input_Lugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
    
}
